[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps =
    https://github.com/ttlappalainen/NMEA2000.git#5b7b9fc3ccc18e30ebfba92da6486cffc6251595
    https://github.com/ttlappalainen/NMEA2000_esp32.git#15cc30887f0e629fbee0821c5b1de03d130728ac
build_flags =
    -Wall
    -Wextra

